
# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Hunter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

source 'https://github.com/cocoapods/specs.git'

  # Pods for Hunter
pod "Alamofire"
  pod 'NVActivityIndicatorView/Extended'
  pod 'Siren'
  pod 'MOLH'
  pod 'TransitionButton'
  pod 'SDWebImage', '~> 5.0'
  pod 'PhoneNumberKit', '~> 2.1'
  pod 'MediaSlideshow'
  #  pod "ImageSlideshow/Alamofire"
  pod "MediaSlideshow/Alamofire"
  pod 'DLRadioButton'
  pod 'OTPFieldView'
  pod 'Cosmos'
  pod "NotificationBannerSwift"
  pod "PMAlertController"
  pod "RAMAnimatedTabBarController"
  pod "MediaSlideshow/AV"
  pod 'DropDown'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'LSDialogViewController'
  pod 'Zoomy'
  pod 'iRecordView'
  pod 'M13Checkbox'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod "TTGSnackbar"
  pod 'IQKeyboardManagerSwift'
  pod 'lottie-ios'
  pod 'Kingfisher'
  pod 'NextGrowingTextView', '1.6.1'
  pod 'WoofTabBarController', :path => '../'
  pod 'FSPagerView'
end
